# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- adf_publish

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    variables:
      dataFactoryName: 'factorygdohx4l7wo7wy'
    steps:
    - publish: $(System.DefaultWorkingDirectory)/$(dataFactoryName)
      artifact: DataFactory

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'Test'
    pool: 
      vmImage: $(vmImageName)
    variables:
      resourceGroupName: 'filechecker-tst-factory-rg'
      dataFactoryName: 'factory4a77dwgfvvzmg'
      keyVaultName: 'keygwu3qy7zy2a3s'
      alphaVantageApiKeyVersion: '1ddb227c18e040f988eb1c26877f5bf0'
      storageAccountName: 'storeiptr3ogmewhhg'
      triggerName: 'DailySchedule-EndOfBusinessDay'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: DataFactory
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Azure Data Factory Deploy: $(dataFactoryName)'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'HotmailAzureSubscription'
              subscriptionId: $(azureSubscriptionId)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(resourceGroupName)
              location: $(azureLocation)
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/DataFactory/ARMTemplateForFactory.json'
              csmParametersFile: '$(Pipeline.Workspace)/DataFactory/ARMTemplateParametersForFactory.json'
              overrideParameters: '-factoryName $(dataFactoryName) -Copy_Alpha_Vantage_to_ADLS_properties_0_typeProperties https://$(keyVaultName).vault.azure.net/secrets/alpha-vantage-api-key/$(alphaVantageApiKeyVersion)?api-version=7.0 -AzureDataLakeStorage1_properties_typeProperties https://$(storageAccountName).dfs.core.windows.net'
              deploymentMode: 'Incremental'
          - task: AzurePowerShell@5
            displayName: 'Azure Data Factory Trigger Start: $(triggerName)'
            inputs:
              azureSubscription: 'HotmailAzureSubscription'
              ScriptType: 'InlineScript'
              Inline: 'Start-AzDataFactoryV2Trigger -ResourceGroupName $(resourceGroupName) -DataFactoryName $(dataFactoryName) -TriggerName $(triggerName) -Force'
              azurePowerShellVersion: 'LatestVersion'